name: Cricket Poll Bot

on:
  workflow_dispatch: # Manual Start
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein restart hoga (Free limit ke liye)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Deps
        run: pip install -r requirements.txt

      - name: Start Bot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: python bot.py
